package br.com.greenwaiver.entities;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ListaProdutoCustoVar generated by hbm2java
 */
@Entity
@Table(name = "ListaProduto_CustoVar", schema = "wpcp")
public class ListaProdutoCustoVar implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	@EmbeddedId
	private ListaProdutoCustoVarId id;

	public ListaProdutoCustoVar() {
	}

	public ListaProdutoCustoVar(ListaProdutoCustoVarId id) {
		this.id = id;
	}

	public ListaProdutoCustoVarId getId() {
		return this.id;
	}

	public void setId(ListaProdutoCustoVarId id) {
		this.id = id;
	}

}
