package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ListaProduto generated by hbm2java
 */
@Entity
@Table(name = "ListaProduto", schema = "wpcp")
public class ListaProduto implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	private String idListaProduto;
	private String cdChamada;
	private String dsListaproduto;
	@ManyToOne
	@JoinColumn(name = "IdProduto", referencedColumnName = "IdProduto")
	private Produto produto;
	private Character stPrincipal;
	private Character stAtivo;
	private String dsObservacao;
	private Double alqDesperdicio;
	private Double alqIndiceMarkup;
	private Double totAlqCustosVar;
	private Character tpCusto;
	private Character stAtualizaPreco;
	private Double alqProcesso;
	private Character stAglutinarProdIguaisNaSubOrdem;
	private String idUsuarioUltimaAlteracao;
	private Date dtUltimaAlteracao;
	private Double qtFatorRendimento;
	private Boolean checkedVersao;
	private String versao;
	private String idInformacaoGeral;

	@OneToMany(fetch = FetchType.LAZY)
	@JoinColumn(name = "IdListaProduto", referencedColumnName = "IdListaProduto")
	private List<ListaProdutoItem> itens = new ArrayList<>();

	public ListaProduto() {
	}

	public ListaProduto(String idListaProduto) {
		this.idListaProduto = idListaProduto;
	}

	public ListaProduto(String idListaProduto, String cdChamada, String dsListaproduto, Produto produto,
			Character stPrincipal, Character stAtivo, String dsObservacao, Double alqDesperdicio,
			Double alqIndiceMarkup, Double totAlqCustosVar, Character tpCusto, Character stAtualizaPreco,
			Double alqProcesso, Character stAglutinarProdIguaisNaSubOrdem, String idUsuarioUltimaAlteracao,
			Date dtUltimaAlteracao, Double qtFatorRendimento, Boolean checkedVersao, String versao,
			String idInformacaoGeral) {
		this.idListaProduto = idListaProduto;
		this.cdChamada = cdChamada;
		this.dsListaproduto = dsListaproduto;
		this.produto = produto;
		this.stPrincipal = stPrincipal;
		this.stAtivo = stAtivo;
		this.dsObservacao = dsObservacao;
		this.alqDesperdicio = alqDesperdicio;
		this.alqIndiceMarkup = alqIndiceMarkup;
		this.totAlqCustosVar = totAlqCustosVar;
		this.tpCusto = tpCusto;
		this.stAtualizaPreco = stAtualizaPreco;
		this.alqProcesso = alqProcesso;
		this.stAglutinarProdIguaisNaSubOrdem = stAglutinarProdIguaisNaSubOrdem;
		this.idUsuarioUltimaAlteracao = idUsuarioUltimaAlteracao;
		this.dtUltimaAlteracao = dtUltimaAlteracao;
		this.qtFatorRendimento = qtFatorRendimento;
		this.checkedVersao = checkedVersao;
		this.versao = versao;
		this.idInformacaoGeral = idInformacaoGeral;
	}

	public List<ListaProdutoItem> getItens() {
		return itens;
	}

	public void setItens(List<ListaProdutoItem> itens) {
		this.itens = itens;
	}

	public String getIdListaProduto() {
		return this.idListaProduto;
	}

	public void setIdListaProduto(String idListaProduto) {
		this.idListaProduto = idListaProduto;
	}

	public String getCdChamada() {
		return this.cdChamada;
	}

	public void setCdChamada(String cdChamada) {
		this.cdChamada = cdChamada;
	}

	public String getDsListaproduto() {
		return this.dsListaproduto;
	}

	public void setDsListaproduto(String dsListaproduto) {
		this.dsListaproduto = dsListaproduto;
	}

	public Produto getProduto() {
		return produto;
	}

	public void setProduto(Produto produto) {
		this.produto = produto;
	}

	public Character getStPrincipal() {
		return this.stPrincipal;
	}

	public void setStPrincipal(Character stPrincipal) {
		this.stPrincipal = stPrincipal;
	}

	public Character getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Character stAtivo) {
		this.stAtivo = stAtivo;
	}

	public String getDsObservacao() {
		return this.dsObservacao;
	}

	public void setDsObservacao(String dsObservacao) {
		this.dsObservacao = dsObservacao;
	}

	public Double getAlqDesperdicio() {
		return this.alqDesperdicio;
	}

	public void setAlqDesperdicio(Double alqDesperdicio) {
		this.alqDesperdicio = alqDesperdicio;
	}

	public Double getAlqIndiceMarkup() {
		return this.alqIndiceMarkup;
	}

	public void setAlqIndiceMarkup(Double alqIndiceMarkup) {
		this.alqIndiceMarkup = alqIndiceMarkup;
	}

	public Double getTotAlqCustosVar() {
		return this.totAlqCustosVar;
	}

	public void setTotAlqCustosVar(Double totAlqCustosVar) {
		this.totAlqCustosVar = totAlqCustosVar;
	}

	public Character getTpCusto() {
		return this.tpCusto;
	}

	public void setTpCusto(Character tpCusto) {
		this.tpCusto = tpCusto;
	}

	public Character getStAtualizaPreco() {
		return this.stAtualizaPreco;
	}

	public void setStAtualizaPreco(Character stAtualizaPreco) {
		this.stAtualizaPreco = stAtualizaPreco;
	}

	public Double getAlqProcesso() {
		return this.alqProcesso;
	}

	public void setAlqProcesso(Double alqProcesso) {
		this.alqProcesso = alqProcesso;
	}

	public Character getStAglutinarProdIguaisNaSubOrdem() {
		return this.stAglutinarProdIguaisNaSubOrdem;
	}

	public void setStAglutinarProdIguaisNaSubOrdem(Character stAglutinarProdIguaisNaSubOrdem) {
		this.stAglutinarProdIguaisNaSubOrdem = stAglutinarProdIguaisNaSubOrdem;
	}

	public String getIdUsuarioUltimaAlteracao() {
		return this.idUsuarioUltimaAlteracao;
	}

	public void setIdUsuarioUltimaAlteracao(String idUsuarioUltimaAlteracao) {
		this.idUsuarioUltimaAlteracao = idUsuarioUltimaAlteracao;
	}

	public Date getDtUltimaAlteracao() {
		return this.dtUltimaAlteracao;
	}

	public void setDtUltimaAlteracao(Date dtUltimaAlteracao) {
		this.dtUltimaAlteracao = dtUltimaAlteracao;
	}

	public Double getQtFatorRendimento() {
		return this.qtFatorRendimento;
	}

	public void setQtFatorRendimento(Double qtFatorRendimento) {
		this.qtFatorRendimento = qtFatorRendimento;
	}

	public Boolean getCheckedVersao() {
		return this.checkedVersao;
	}

	public void setCheckedVersao(Boolean checkedVersao) {
		this.checkedVersao = checkedVersao;
	}

	public String getVersao() {
		return this.versao;
	}

	public void setVersao(String versao) {
		this.versao = versao;
	}

	public String getIdInformacaoGeral() {
		return this.idInformacaoGeral;
	}

	public void setIdInformacaoGeral(String idInformacaoGeral) {
		this.idInformacaoGeral = idInformacaoGeral;
	}

	@Override
	public String toString() {
		return "ListaProduto [idListaProduto=" + idListaProduto + ", cdChamada=" + cdChamada + ", dsListaproduto="
				+ dsListaproduto + ", produto=" + produto + ", stPrincipal=" + stPrincipal + ", stAtivo=" + stAtivo
				+ ", dsObservacao=" + dsObservacao + ", alqDesperdicio=" + alqDesperdicio + ", alqIndiceMarkup="
				+ alqIndiceMarkup + ", totAlqCustosVar=" + totAlqCustosVar + ", tpCusto=" + tpCusto
				+ ", stAtualizaPreco=" + stAtualizaPreco + ", alqProcesso=" + alqProcesso
				+ ", stAglutinarProdIguaisNaSubOrdem=" + stAglutinarProdIguaisNaSubOrdem + ", idUsuarioUltimaAlteracao="
				+ idUsuarioUltimaAlteracao + ", dtUltimaAlteracao=" + dtUltimaAlteracao + ", qtFatorRendimento="
				+ qtFatorRendimento + ", checkedVersao=" + checkedVersao + ", versao=" + versao + ", idInformacaoGeral="
				+ idInformacaoGeral + "]";
	}

}
