package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ListaProdutoPrecoId generated by hbm2java
 */
public class ListaProdutoPrecoId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idListaProduto;
	private String idProduto;
	private String idPreco;
	private String cdPreco;
	private String nmPreco;
	private Character stAtivoCalculo;
	private Character tpPreco;

	public ListaProdutoPrecoId() {
	}

	public ListaProdutoPrecoId(String idListaProduto, String idProduto, String idPreco, String cdPreco, String nmPreco,
			Character stAtivoCalculo, Character tpPreco) {
		this.idListaProduto = idListaProduto;
		this.idProduto = idProduto;
		this.idPreco = idPreco;
		this.cdPreco = cdPreco;
		this.nmPreco = nmPreco;
		this.stAtivoCalculo = stAtivoCalculo;
		this.tpPreco = tpPreco;
	}

	public String getIdListaProduto() {
		return this.idListaProduto;
	}

	public void setIdListaProduto(String idListaProduto) {
		this.idListaProduto = idListaProduto;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public String getIdPreco() {
		return this.idPreco;
	}

	public void setIdPreco(String idPreco) {
		this.idPreco = idPreco;
	}

	public String getCdPreco() {
		return this.cdPreco;
	}

	public void setCdPreco(String cdPreco) {
		this.cdPreco = cdPreco;
	}

	public String getNmPreco() {
		return this.nmPreco;
	}

	public void setNmPreco(String nmPreco) {
		this.nmPreco = nmPreco;
	}

	public Character getStAtivoCalculo() {
		return this.stAtivoCalculo;
	}

	public void setStAtivoCalculo(Character stAtivoCalculo) {
		this.stAtivoCalculo = stAtivoCalculo;
	}

	public Character getTpPreco() {
		return this.tpPreco;
	}

	public void setTpPreco(Character tpPreco) {
		this.tpPreco = tpPreco;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ListaProdutoPrecoId))
			return false;
		ListaProdutoPrecoId castOther = (ListaProdutoPrecoId) other;

		return ((this.getIdListaProduto() == castOther.getIdListaProduto())
				|| (this.getIdListaProduto() != null && castOther.getIdListaProduto() != null
						&& this.getIdListaProduto().equals(castOther.getIdListaProduto())))
				&& ((this.getIdProduto() == castOther.getIdProduto()) || (this.getIdProduto() != null
						&& castOther.getIdProduto() != null && this.getIdProduto().equals(castOther.getIdProduto())))
				&& ((this.getIdPreco() == castOther.getIdPreco()) || (this.getIdPreco() != null
						&& castOther.getIdPreco() != null && this.getIdPreco().equals(castOther.getIdPreco())))
				&& ((this.getCdPreco() == castOther.getCdPreco()) || (this.getCdPreco() != null
						&& castOther.getCdPreco() != null && this.getCdPreco().equals(castOther.getCdPreco())))
				&& ((this.getNmPreco() == castOther.getNmPreco()) || (this.getNmPreco() != null
						&& castOther.getNmPreco() != null && this.getNmPreco().equals(castOther.getNmPreco())))
				&& ((this.getStAtivoCalculo() == castOther.getStAtivoCalculo())
						|| (this.getStAtivoCalculo() != null && castOther.getStAtivoCalculo() != null
								&& this.getStAtivoCalculo().equals(castOther.getStAtivoCalculo())))
				&& ((this.getTpPreco() == castOther.getTpPreco()) || (this.getTpPreco() != null
						&& castOther.getTpPreco() != null && this.getTpPreco().equals(castOther.getTpPreco())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdListaProduto() == null ? 0 : this.getIdListaProduto().hashCode());
		result = 37 * result + (getIdProduto() == null ? 0 : this.getIdProduto().hashCode());
		result = 37 * result + (getIdPreco() == null ? 0 : this.getIdPreco().hashCode());
		result = 37 * result + (getCdPreco() == null ? 0 : this.getCdPreco().hashCode());
		result = 37 * result + (getNmPreco() == null ? 0 : this.getNmPreco().hashCode());
		result = 37 * result + (getStAtivoCalculo() == null ? 0 : this.getStAtivoCalculo().hashCode());
		result = 37 * result + (getTpPreco() == null ? 0 : this.getTpPreco().hashCode());
		return result;
	}

}
