package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;
import org.hibernate.annotations.Where;

/**
 * Produto generated by hbm2java
 */
@Entity
@Table(name = "Produto", schema = "dbo")
public class Produto implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	private String idProduto;

	@OneToMany
	@Where(clause = "stCodigoPrincipal = 'S' ")
	@JoinColumn(name = "IdProduto", referencedColumnName = "IdProduto")
	private Set<CodigoProduto> codigos = new HashSet<>();
	
	@OneToMany
	@JoinColumn(name = "IdProduto", referencedColumnName = "IdProduto")
	private Set<ProdutoEmpresa> empresas = new HashSet<>();
	private String cdClassificacao;

	private String idProdutoMaster;
	private String cdTratamentoEspecial;
	private String idGradeProdutoDetalheV;
	private String nmProduto;
	private Character stAtivo;
	private String idGradeProdutoDetalheH;
	@ManyToOne
	@JoinColumn(name="IdGrupoProduto", referencedColumnName = "IdGrupoProduto")
	private GrupoProduto grupo;
	
	@ManyToOne
	@JoinColumn(name="IdUnidade", referencedColumnName = "IdUnidade")	
	private Unidade unidade;
	private String dsObservacao;
	private Double ftConversaoUnidade;
	private String idProdutoOrigem;
	private Double qtEmbalagem;
	private Double vlPesoLiquido;
	private Character stCobraEmbalagem;
	private Double vlPesoBruto;
	private String idCalculoIcms;
	private String idClassificacaoFiscal;
	private Character stProdutoComposto;
	private Double vlPrecoMaximoDeCompra;
	private Double alLucroProduto;
	private Character stControlaLote;
	private Character tpClassificacaoAbc;
	private Integer nrRanking;
	private Character stServico;
	private Double alRepasse;
	private String idCategoriaRepasse;
	private String idImagem;
	private String idElementoQuimicoAtivo;
	private Integer nrDiasAtendimento;
	private String nmUsuariosAtendimento;
	private Double alDesconto;
	private Double vlDesconto;
	private Character stEditaDescontoPdv;
	private Double qtVolume;
	private Integer hrMontagem;
	private Character tpPorte;
	private Integer nrDiasReposicao;
	private Character tpProduto;
	private Character stQtdePesoCheckoutPdv;
	private Character tpOrigemProduto;
	private Character stRepasse;
	private Character stEditaPeso;
	private Character stComposicaoFlexivel;
	private Character tpEtiqueta;
	private Character tpRepasse;
	private Double alRepassePedido;
	private Double alRepasseDuplicata;
	private Character stProdutoCompostoKit;
	private String cdCfop;
	private String idCalculoIssdestino;
	private String idUnidadeEmbalagem;
	
	@ManyToOne
	@JoinColumn(name="IdFamiliaProduto")
	private FamiliaProduto familia;
	private LocalDate dtCadastro;
	private Character tpMontagem;
	private Character stDesoneraIcms;
	private Character stControlaNrSerie;
	private Integer qtProdutoComposicaoOptativa;
	private Double vlBonificacao;
	private Double alBonificacao;
	private Character stMultiploVolume;
	private Character stCalculaPis;
	private Character stCalculaCofins;
	private Character stCalculaCsll;
	private String cdCfopentreUf;
	private String cdCfopdevolucaoIntraUf;
	private String cdCfopdevolucaoEntreUf;
	private Character stAtivoCompra;
	private Character stControlaSelo;
	private Double ftConversaoClasseEnquadramento;
	private String cdClassificacaoDipi;
	private Character stSujeitoRegimeSubstTribut;
	private Character stCompletarEmbalagem;
	private Double vlLargura;
	private Double vlRendimento;
	private Character stRestricaoComplQuantIg;
	private String cdProdepDipi;
	private String cdSeloControleIpi;
	private String idClasseEnquadramento;
	private String cdExTipi;
	private Double qtUnidadePorSelo;
	private String idGeneroProduto;
	private Double alCofins;
	private Double alPis;
	private Character stAlCofinsporUnidade;
	private Character stAlPisporUnidade;
	private Character tpProdutoComplementar;
	private Character tpModalidadeBaseSt;
	private String dsPrecoMaximoConsumidor;
	private Double vlPrecoMaximoConsumidor;
	private Character stEmiteEtiqueta;
	private Integer nrDiasValidade;
	private String cdListaServico;
	@Transient
	private byte[] versaoRegistro;
	private String idUnidadeComparacao;
	private Double ftConversaoComparacao;
	private Integer nrTempoExecucaoServico;
	private String idServicoSped;
	private Double alMargemLucro;
	private String cdSituacaoTributariaPis;
	private String cdSituacaoTributariaCofins;
	private Character stTributacaoEspecifica;
	private String cdSitTributPissaida;
	private String cdSitTributCofinssaida;
	private String cdSitTributPisentrada;
	private String cdSitTributCofinsentrada;
	private String nmCurto;
	private BigDecimal ftAcrescimoValorVenda;
	private Character stProdutoIsstributadoIcms;
	private Integer idCest;
	private Double vlAliquotaPis;
	private Double vlAliquotaCofins;
	private Character tpEmbalagem;
	private Double vlAltura;
	private Double vlProfundidade;
	private Double vlDiametro;
	private boolean stVendaPorTamanho;
	private boolean stSujeitoRegularizacaoSanitaria;
	private String cdAnvisa;
	private char tpCalculoQuantidadeEmbalagem;
	private Date dtAlteracao;
	private Integer idClassificacaoTelecomunicacao;
	private boolean stBloqueiaCriacaoAtendimento;
	private String cdBeneficioFiscal;
	private String dsMotivoIsencaoAnvisa;
	private String idProdutoOrigemMovimento;
	private Double ftConversaoUnidadeMovimento;

	// PCP
	
	@OneToOne
	@NotFound(action = NotFoundAction.IGNORE)
	@JoinColumn(name = "IdProduto", referencedColumnName = "IdProduto")
	private ProdutoPcp pcp;

	public Produto() {
	}

	public Produto(String idProduto, boolean stVendaPorTamanho, boolean stSujeitoRegularizacaoSanitaria,
			char tpCalculoQuantidadeEmbalagem, boolean stBloqueiaCriacaoAtendimento) {
		this.idProduto = idProduto;
		this.stVendaPorTamanho = stVendaPorTamanho;
		this.stSujeitoRegularizacaoSanitaria = stSujeitoRegularizacaoSanitaria;
		this.tpCalculoQuantidadeEmbalagem = tpCalculoQuantidadeEmbalagem;
		this.stBloqueiaCriacaoAtendimento = stBloqueiaCriacaoAtendimento;
	}

	public Produto(String idProduto, String cdClassificacao, String idProdutoMaster, String cdTratamentoEspecial,
			String idGradeProdutoDetalheV, String nmProduto, Character stAtivo, String idGradeProdutoDetalheH,
			GrupoProduto grupo, Unidade unidade, String dsObservacao, Double ftConversaoUnidade,
			String idProdutoOrigem, Double qtEmbalagem, Double vlPesoLiquido, Character stCobraEmbalagem,
			Double vlPesoBruto, String idCalculoIcms, String idClassificacaoFiscal, Character stProdutoComposto,
			Double vlPrecoMaximoDeCompra, Double alLucroProduto, Character stControlaLote, Character tpClassificacaoAbc,
			Integer nrRanking, Character stServico, Double alRepasse, String idCategoriaRepasse, String idImagem,
			String idElementoQuimicoAtivo, Integer nrDiasAtendimento, String nmUsuariosAtendimento, Double alDesconto,
			Double vlDesconto, Character stEditaDescontoPdv, Double qtVolume, Integer hrMontagem, Character tpPorte,
			Integer nrDiasReposicao, Character tpProduto, Character stQtdePesoCheckoutPdv, Character tpOrigemProduto,
			Character stRepasse, Character stEditaPeso, Character stComposicaoFlexivel, Character tpEtiqueta,
			Character tpRepasse, Double alRepassePedido, Double alRepasseDuplicata, Character stProdutoCompostoKit,
			String cdCfop, String idCalculoIssdestino, String idUnidadeEmbalagem, FamiliaProduto familia,
			LocalDate dtCadastro, Character tpMontagem, Character stDesoneraIcms, Character stControlaNrSerie,
			Integer qtProdutoComposicaoOptativa, Double vlBonificacao, Double alBonificacao, Character stMultiploVolume,
			Character stCalculaPis, Character stCalculaCofins, Character stCalculaCsll, String cdCfopentreUf,
			String cdCfopdevolucaoIntraUf, String cdCfopdevolucaoEntreUf, Character stAtivoCompra,
			Character stControlaSelo, Double ftConversaoClasseEnquadramento, String cdClassificacaoDipi,
			Character stSujeitoRegimeSubstTribut, Character stCompletarEmbalagem, Double vlLargura, Double vlRendimento,
			Character stRestricaoComplQuantIg, String cdProdepDipi, String cdSeloControleIpi,
			String idClasseEnquadramento, String cdExTipi, Double qtUnidadePorSelo, String idGeneroProduto,
			Double alCofins, Double alPis, Character stAlCofinsporUnidade, Character stAlPisporUnidade,
			Character tpProdutoComplementar, Character tpModalidadeBaseSt, String dsPrecoMaximoConsumidor,
			Double vlPrecoMaximoConsumidor, Character stEmiteEtiqueta, Integer nrDiasValidade, String cdListaServico,
			byte[] versaoRegistro, String idUnidadeComparacao, Double ftConversaoComparacao,
			Integer nrTempoExecucaoServico, String idServicoSped, Double alMargemLucro, String cdSituacaoTributariaPis,
			String cdSituacaoTributariaCofins, Character stTributacaoEspecifica, String cdSitTributPissaida,
			String cdSitTributCofinssaida, String cdSitTributPisentrada, String cdSitTributCofinsentrada,
			String nmCurto, BigDecimal ftAcrescimoValorVenda, Character stProdutoIsstributadoIcms, Integer idCest,
			Double vlAliquotaPis, Double vlAliquotaCofins, Character tpEmbalagem, Double vlAltura,
			Double vlProfundidade, Double vlDiametro, boolean stVendaPorTamanho,
			boolean stSujeitoRegularizacaoSanitaria, String cdAnvisa, char tpCalculoQuantidadeEmbalagem,
			Date dtAlteracao, Integer idClassificacaoTelecomunicacao, boolean stBloqueiaCriacaoAtendimento,
			String cdBeneficioFiscal, String dsMotivoIsencaoAnvisa, String idProdutoOrigemMovimento,
			Double ftConversaoUnidadeMovimento) {
		this.idProduto = idProduto;
		this.cdClassificacao = cdClassificacao;
		this.idProdutoMaster = idProdutoMaster;
		this.cdTratamentoEspecial = cdTratamentoEspecial;
		this.idGradeProdutoDetalheV = idGradeProdutoDetalheV;
		this.nmProduto = nmProduto;
		this.stAtivo = stAtivo;
		this.idGradeProdutoDetalheH = idGradeProdutoDetalheH;
		this.grupo = grupo;
		this.unidade = unidade;
		this.dsObservacao = dsObservacao;
		this.ftConversaoUnidade = ftConversaoUnidade;
		this.idProdutoOrigem = idProdutoOrigem;
		this.qtEmbalagem = qtEmbalagem;
		this.vlPesoLiquido = vlPesoLiquido;
		this.stCobraEmbalagem = stCobraEmbalagem;
		this.vlPesoBruto = vlPesoBruto;
		this.idCalculoIcms = idCalculoIcms;
		this.idClassificacaoFiscal = idClassificacaoFiscal;
		this.stProdutoComposto = stProdutoComposto;
		this.vlPrecoMaximoDeCompra = vlPrecoMaximoDeCompra;
		this.alLucroProduto = alLucroProduto;
		this.stControlaLote = stControlaLote;
		this.tpClassificacaoAbc = tpClassificacaoAbc;
		this.nrRanking = nrRanking;
		this.stServico = stServico;
		this.alRepasse = alRepasse;
		this.idCategoriaRepasse = idCategoriaRepasse;
		this.idImagem = idImagem;
		this.idElementoQuimicoAtivo = idElementoQuimicoAtivo;
		this.nrDiasAtendimento = nrDiasAtendimento;
		this.nmUsuariosAtendimento = nmUsuariosAtendimento;
		this.alDesconto = alDesconto;
		this.vlDesconto = vlDesconto;
		this.stEditaDescontoPdv = stEditaDescontoPdv;
		this.qtVolume = qtVolume;
		this.hrMontagem = hrMontagem;
		this.tpPorte = tpPorte;
		this.nrDiasReposicao = nrDiasReposicao;
		this.tpProduto = tpProduto;
		this.stQtdePesoCheckoutPdv = stQtdePesoCheckoutPdv;
		this.tpOrigemProduto = tpOrigemProduto;
		this.stRepasse = stRepasse;
		this.stEditaPeso = stEditaPeso;
		this.stComposicaoFlexivel = stComposicaoFlexivel;
		this.tpEtiqueta = tpEtiqueta;
		this.tpRepasse = tpRepasse;
		this.alRepassePedido = alRepassePedido;
		this.alRepasseDuplicata = alRepasseDuplicata;
		this.stProdutoCompostoKit = stProdutoCompostoKit;
		this.cdCfop = cdCfop;
		this.idCalculoIssdestino = idCalculoIssdestino;
		this.idUnidadeEmbalagem = idUnidadeEmbalagem;
		this.familia = familia;
		this.dtCadastro = dtCadastro;
		this.tpMontagem = tpMontagem;
		this.stDesoneraIcms = stDesoneraIcms;
		this.stControlaNrSerie = stControlaNrSerie;
		this.qtProdutoComposicaoOptativa = qtProdutoComposicaoOptativa;
		this.vlBonificacao = vlBonificacao;
		this.alBonificacao = alBonificacao;
		this.stMultiploVolume = stMultiploVolume;
		this.stCalculaPis = stCalculaPis;
		this.stCalculaCofins = stCalculaCofins;
		this.stCalculaCsll = stCalculaCsll;
		this.cdCfopentreUf = cdCfopentreUf;
		this.cdCfopdevolucaoIntraUf = cdCfopdevolucaoIntraUf;
		this.cdCfopdevolucaoEntreUf = cdCfopdevolucaoEntreUf;
		this.stAtivoCompra = stAtivoCompra;
		this.stControlaSelo = stControlaSelo;
		this.ftConversaoClasseEnquadramento = ftConversaoClasseEnquadramento;
		this.cdClassificacaoDipi = cdClassificacaoDipi;
		this.stSujeitoRegimeSubstTribut = stSujeitoRegimeSubstTribut;
		this.stCompletarEmbalagem = stCompletarEmbalagem;
		this.vlLargura = vlLargura;
		this.vlRendimento = vlRendimento;
		this.stRestricaoComplQuantIg = stRestricaoComplQuantIg;
		this.cdProdepDipi = cdProdepDipi;
		this.cdSeloControleIpi = cdSeloControleIpi;
		this.idClasseEnquadramento = idClasseEnquadramento;
		this.cdExTipi = cdExTipi;
		this.qtUnidadePorSelo = qtUnidadePorSelo;
		this.idGeneroProduto = idGeneroProduto;
		this.alCofins = alCofins;
		this.alPis = alPis;
		this.stAlCofinsporUnidade = stAlCofinsporUnidade;
		this.stAlPisporUnidade = stAlPisporUnidade;
		this.tpProdutoComplementar = tpProdutoComplementar;
		this.tpModalidadeBaseSt = tpModalidadeBaseSt;
		this.dsPrecoMaximoConsumidor = dsPrecoMaximoConsumidor;
		this.vlPrecoMaximoConsumidor = vlPrecoMaximoConsumidor;
		this.stEmiteEtiqueta = stEmiteEtiqueta;
		this.nrDiasValidade = nrDiasValidade;
		this.cdListaServico = cdListaServico;
		this.versaoRegistro = versaoRegistro;
		this.idUnidadeComparacao = idUnidadeComparacao;
		this.ftConversaoComparacao = ftConversaoComparacao;
		this.nrTempoExecucaoServico = nrTempoExecucaoServico;
		this.idServicoSped = idServicoSped;
		this.alMargemLucro = alMargemLucro;
		this.cdSituacaoTributariaPis = cdSituacaoTributariaPis;
		this.cdSituacaoTributariaCofins = cdSituacaoTributariaCofins;
		this.stTributacaoEspecifica = stTributacaoEspecifica;
		this.cdSitTributPissaida = cdSitTributPissaida;
		this.cdSitTributCofinssaida = cdSitTributCofinssaida;
		this.cdSitTributPisentrada = cdSitTributPisentrada;
		this.cdSitTributCofinsentrada = cdSitTributCofinsentrada;
		this.nmCurto = nmCurto;
		this.ftAcrescimoValorVenda = ftAcrescimoValorVenda;
		this.stProdutoIsstributadoIcms = stProdutoIsstributadoIcms;
		this.idCest = idCest;
		this.vlAliquotaPis = vlAliquotaPis;
		this.vlAliquotaCofins = vlAliquotaCofins;
		this.tpEmbalagem = tpEmbalagem;
		this.vlAltura = vlAltura;
		this.vlProfundidade = vlProfundidade;
		this.vlDiametro = vlDiametro;
		this.stVendaPorTamanho = stVendaPorTamanho;
		this.stSujeitoRegularizacaoSanitaria = stSujeitoRegularizacaoSanitaria;
		this.cdAnvisa = cdAnvisa;
		this.tpCalculoQuantidadeEmbalagem = tpCalculoQuantidadeEmbalagem;
		this.dtAlteracao = dtAlteracao;
		this.idClassificacaoTelecomunicacao = idClassificacaoTelecomunicacao;
		this.stBloqueiaCriacaoAtendimento = stBloqueiaCriacaoAtendimento;
		this.cdBeneficioFiscal = cdBeneficioFiscal;
		this.dsMotivoIsencaoAnvisa = dsMotivoIsencaoAnvisa;
		this.idProdutoOrigemMovimento = idProdutoOrigemMovimento;
		this.ftConversaoUnidadeMovimento = ftConversaoUnidadeMovimento;
	}
	
	

	public Set<ProdutoEmpresa> getEmpresas() {
		return empresas;
	}

	public void setEmpresas(Set<ProdutoEmpresa> empresas) {
		this.empresas = empresas;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public Set<CodigoProduto> getCodigos() {
		return codigos;
	}

	public void setCodigos(Set<CodigoProduto> codigos) {
		this.codigos = codigos;
	}

	public String getCdClassificacao() {
		return this.cdClassificacao;
	}

	public void setCdClassificacao(String cdClassificacao) {
		this.cdClassificacao = cdClassificacao;
	}

	public String getIdProdutoMaster() {
		return this.idProdutoMaster;
	}

	public void setIdProdutoMaster(String idProdutoMaster) {
		this.idProdutoMaster = idProdutoMaster;
	}

	public String getCdTratamentoEspecial() {
		return this.cdTratamentoEspecial;
	}

	public void setCdTratamentoEspecial(String cdTratamentoEspecial) {
		this.cdTratamentoEspecial = cdTratamentoEspecial;
	}

	public String getIdGradeProdutoDetalheV() {
		return this.idGradeProdutoDetalheV;
	}

	public void setIdGradeProdutoDetalheV(String idGradeProdutoDetalheV) {
		this.idGradeProdutoDetalheV = idGradeProdutoDetalheV;
	}

	public String getNmProduto() {
		return this.nmProduto;
	}

	public void setNmProduto(String nmProduto) {
		this.nmProduto = nmProduto;
	}

	public Character getStAtivo() {
		return this.stAtivo;
	}

	public void setStAtivo(Character stAtivo) {
		this.stAtivo = stAtivo;
	}

	public String getIdGradeProdutoDetalheH() {
		return this.idGradeProdutoDetalheH;
	}

	public void setIdGradeProdutoDetalheH(String idGradeProdutoDetalheH) {
		this.idGradeProdutoDetalheH = idGradeProdutoDetalheH;
	}

	public GrupoProduto getGrupoProduto() {
		return this.grupo;
	}

	public void setGrupoProduto(GrupoProduto grupoProduto) {
		this.grupo = grupoProduto;
	}

	public Unidade getUnidade() {
		return this.unidade;
	}

	public void setIdUnidade(Unidade unidade) {
		this.unidade = unidade;
	}

	public String getDsObservacao() {
		return this.dsObservacao;
	}

	public void setDsObservacao(String dsObservacao) {
		this.dsObservacao = dsObservacao;
	}

	public Double getFtConversaoUnidade() {
		return this.ftConversaoUnidade;
	}

	public void setFtConversaoUnidade(Double ftConversaoUnidade) {
		this.ftConversaoUnidade = ftConversaoUnidade;
	}

	public String getIdProdutoOrigem() {
		return this.idProdutoOrigem;
	}

	public void setIdProdutoOrigem(String idProdutoOrigem) {
		this.idProdutoOrigem = idProdutoOrigem;
	}

	public Double getQtEmbalagem() {
		return this.qtEmbalagem;
	}

	public void setQtEmbalagem(Double qtEmbalagem) {
		this.qtEmbalagem = qtEmbalagem;
	}

	public Double getVlPesoLiquido() {
		return this.vlPesoLiquido;
	}

	public void setVlPesoLiquido(Double vlPesoLiquido) {
		this.vlPesoLiquido = vlPesoLiquido;
	}

	public Character getStCobraEmbalagem() {
		return this.stCobraEmbalagem;
	}

	public void setStCobraEmbalagem(Character stCobraEmbalagem) {
		this.stCobraEmbalagem = stCobraEmbalagem;
	}

	public Double getVlPesoBruto() {
		return this.vlPesoBruto;
	}

	public void setVlPesoBruto(Double vlPesoBruto) {
		this.vlPesoBruto = vlPesoBruto;
	}

	public String getIdCalculoIcms() {
		return this.idCalculoIcms;
	}

	public void setIdCalculoIcms(String idCalculoIcms) {
		this.idCalculoIcms = idCalculoIcms;
	}

	public String getIdClassificacaoFiscal() {
		return this.idClassificacaoFiscal;
	}

	public void setIdClassificacaoFiscal(String idClassificacaoFiscal) {
		this.idClassificacaoFiscal = idClassificacaoFiscal;
	}

	public Character getStProdutoComposto() {
		return this.stProdutoComposto;
	}

	public void setStProdutoComposto(Character stProdutoComposto) {
		this.stProdutoComposto = stProdutoComposto;
	}

	public Double getVlPrecoMaximoDeCompra() {
		return this.vlPrecoMaximoDeCompra;
	}

	public void setVlPrecoMaximoDeCompra(Double vlPrecoMaximoDeCompra) {
		this.vlPrecoMaximoDeCompra = vlPrecoMaximoDeCompra;
	}

	public Double getAlLucroProduto() {
		return this.alLucroProduto;
	}

	public void setAlLucroProduto(Double alLucroProduto) {
		this.alLucroProduto = alLucroProduto;
	}

	public Character getStControlaLote() {
		return this.stControlaLote;
	}

	public void setStControlaLote(Character stControlaLote) {
		this.stControlaLote = stControlaLote;
	}

	public Character getTpClassificacaoAbc() {
		return this.tpClassificacaoAbc;
	}

	public void setTpClassificacaoAbc(Character tpClassificacaoAbc) {
		this.tpClassificacaoAbc = tpClassificacaoAbc;
	}

	public Integer getNrRanking() {
		return this.nrRanking;
	}

	public void setNrRanking(Integer nrRanking) {
		this.nrRanking = nrRanking;
	}

	public Character getStServico() {
		return this.stServico;
	}

	public void setStServico(Character stServico) {
		this.stServico = stServico;
	}

	public Double getAlRepasse() {
		return this.alRepasse;
	}

	public void setAlRepasse(Double alRepasse) {
		this.alRepasse = alRepasse;
	}

	public String getIdCategoriaRepasse() {
		return this.idCategoriaRepasse;
	}

	public void setIdCategoriaRepasse(String idCategoriaRepasse) {
		this.idCategoriaRepasse = idCategoriaRepasse;
	}

	public String getIdImagem() {
		return this.idImagem;
	}

	public void setIdImagem(String idImagem) {
		this.idImagem = idImagem;
	}

	public String getIdElementoQuimicoAtivo() {
		return this.idElementoQuimicoAtivo;
	}

	public void setIdElementoQuimicoAtivo(String idElementoQuimicoAtivo) {
		this.idElementoQuimicoAtivo = idElementoQuimicoAtivo;
	}

	public Integer getNrDiasAtendimento() {
		return this.nrDiasAtendimento;
	}

	public void setNrDiasAtendimento(Integer nrDiasAtendimento) {
		this.nrDiasAtendimento = nrDiasAtendimento;
	}

	public String getNmUsuariosAtendimento() {
		return this.nmUsuariosAtendimento;
	}

	public void setNmUsuariosAtendimento(String nmUsuariosAtendimento) {
		this.nmUsuariosAtendimento = nmUsuariosAtendimento;
	}

	public Double getAlDesconto() {
		return this.alDesconto;
	}

	public void setAlDesconto(Double alDesconto) {
		this.alDesconto = alDesconto;
	}

	public Double getVlDesconto() {
		return this.vlDesconto;
	}

	public void setVlDesconto(Double vlDesconto) {
		this.vlDesconto = vlDesconto;
	}

	public Character getStEditaDescontoPdv() {
		return this.stEditaDescontoPdv;
	}

	public void setStEditaDescontoPdv(Character stEditaDescontoPdv) {
		this.stEditaDescontoPdv = stEditaDescontoPdv;
	}

	public Double getQtVolume() {
		return this.qtVolume;
	}

	public void setQtVolume(Double qtVolume) {
		this.qtVolume = qtVolume;
	}

	public Integer getHrMontagem() {
		return this.hrMontagem;
	}

	public void setHrMontagem(Integer hrMontagem) {
		this.hrMontagem = hrMontagem;
	}

	public Character getTpPorte() {
		return this.tpPorte;
	}

	public void setTpPorte(Character tpPorte) {
		this.tpPorte = tpPorte;
	}

	public Integer getNrDiasReposicao() {
		return this.nrDiasReposicao;
	}

	public void setNrDiasReposicao(Integer nrDiasReposicao) {
		this.nrDiasReposicao = nrDiasReposicao;
	}

	public Character getTpProduto() {
		return this.tpProduto;
	}

	public void setTpProduto(Character tpProduto) {
		this.tpProduto = tpProduto;
	}

	public Character getStQtdePesoCheckoutPdv() {
		return this.stQtdePesoCheckoutPdv;
	}

	public void setStQtdePesoCheckoutPdv(Character stQtdePesoCheckoutPdv) {
		this.stQtdePesoCheckoutPdv = stQtdePesoCheckoutPdv;
	}

	public Character getTpOrigemProduto() {
		return this.tpOrigemProduto;
	}

	public void setTpOrigemProduto(Character tpOrigemProduto) {
		this.tpOrigemProduto = tpOrigemProduto;
	}

	public Character getStRepasse() {
		return this.stRepasse;
	}

	public void setStRepasse(Character stRepasse) {
		this.stRepasse = stRepasse;
	}

	public Character getStEditaPeso() {
		return this.stEditaPeso;
	}

	public void setStEditaPeso(Character stEditaPeso) {
		this.stEditaPeso = stEditaPeso;
	}

	public Character getStComposicaoFlexivel() {
		return this.stComposicaoFlexivel;
	}

	public void setStComposicaoFlexivel(Character stComposicaoFlexivel) {
		this.stComposicaoFlexivel = stComposicaoFlexivel;
	}

	public Character getTpEtiqueta() {
		return this.tpEtiqueta;
	}

	public void setTpEtiqueta(Character tpEtiqueta) {
		this.tpEtiqueta = tpEtiqueta;
	}

	public Character getTpRepasse() {
		return this.tpRepasse;
	}

	public void setTpRepasse(Character tpRepasse) {
		this.tpRepasse = tpRepasse;
	}

	public Double getAlRepassePedido() {
		return this.alRepassePedido;
	}

	public void setAlRepassePedido(Double alRepassePedido) {
		this.alRepassePedido = alRepassePedido;
	}

	public Double getAlRepasseDuplicata() {
		return this.alRepasseDuplicata;
	}

	public void setAlRepasseDuplicata(Double alRepasseDuplicata) {
		this.alRepasseDuplicata = alRepasseDuplicata;
	}

	public Character getStProdutoCompostoKit() {
		return this.stProdutoCompostoKit;
	}

	public void setStProdutoCompostoKit(Character stProdutoCompostoKit) {
		this.stProdutoCompostoKit = stProdutoCompostoKit;
	}

	public String getCdCfop() {
		return this.cdCfop;
	}

	public void setCdCfop(String cdCfop) {
		this.cdCfop = cdCfop;
	}

	public String getIdCalculoIssdestino() {
		return this.idCalculoIssdestino;
	}

	public void setIdCalculoIssdestino(String idCalculoIssdestino) {
		this.idCalculoIssdestino = idCalculoIssdestino;
	}

	public String getIdUnidadeEmbalagem() {
		return this.idUnidadeEmbalagem;
	}

	public void setIdUnidadeEmbalagem(String idUnidadeEmbalagem) {
		this.idUnidadeEmbalagem = idUnidadeEmbalagem;
	}

	public FamiliaProduto getFamiliaProduto() {
		return this.familia;
	}

	public void setFamiliaProduto(FamiliaProduto familia) {
		this.familia = familia;
	}

	public LocalDate getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(LocalDate dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

	public Character getTpMontagem() {
		return this.tpMontagem;
	}

	public void setTpMontagem(Character tpMontagem) {
		this.tpMontagem = tpMontagem;
	}

	public Character getStDesoneraIcms() {
		return this.stDesoneraIcms;
	}

	public void setStDesoneraIcms(Character stDesoneraIcms) {
		this.stDesoneraIcms = stDesoneraIcms;
	}

	public Character getStControlaNrSerie() {
		return this.stControlaNrSerie;
	}

	public void setStControlaNrSerie(Character stControlaNrSerie) {
		this.stControlaNrSerie = stControlaNrSerie;
	}

	public Integer getQtProdutoComposicaoOptativa() {
		return this.qtProdutoComposicaoOptativa;
	}

	public void setQtProdutoComposicaoOptativa(Integer qtProdutoComposicaoOptativa) {
		this.qtProdutoComposicaoOptativa = qtProdutoComposicaoOptativa;
	}

	public Double getVlBonificacao() {
		return this.vlBonificacao;
	}

	public void setVlBonificacao(Double vlBonificacao) {
		this.vlBonificacao = vlBonificacao;
	}

	public Double getAlBonificacao() {
		return this.alBonificacao;
	}

	public void setAlBonificacao(Double alBonificacao) {
		this.alBonificacao = alBonificacao;
	}

	public Character getStMultiploVolume() {
		return this.stMultiploVolume;
	}

	public void setStMultiploVolume(Character stMultiploVolume) {
		this.stMultiploVolume = stMultiploVolume;
	}

	public Character getStCalculaPis() {
		return this.stCalculaPis;
	}

	public void setStCalculaPis(Character stCalculaPis) {
		this.stCalculaPis = stCalculaPis;
	}

	public Character getStCalculaCofins() {
		return this.stCalculaCofins;
	}

	public void setStCalculaCofins(Character stCalculaCofins) {
		this.stCalculaCofins = stCalculaCofins;
	}

	public Character getStCalculaCsll() {
		return this.stCalculaCsll;
	}

	public void setStCalculaCsll(Character stCalculaCsll) {
		this.stCalculaCsll = stCalculaCsll;
	}

	public String getCdCfopentreUf() {
		return this.cdCfopentreUf;
	}

	public void setCdCfopentreUf(String cdCfopentreUf) {
		this.cdCfopentreUf = cdCfopentreUf;
	}

	public String getCdCfopdevolucaoIntraUf() {
		return this.cdCfopdevolucaoIntraUf;
	}

	public void setCdCfopdevolucaoIntraUf(String cdCfopdevolucaoIntraUf) {
		this.cdCfopdevolucaoIntraUf = cdCfopdevolucaoIntraUf;
	}

	public String getCdCfopdevolucaoEntreUf() {
		return this.cdCfopdevolucaoEntreUf;
	}

	public void setCdCfopdevolucaoEntreUf(String cdCfopdevolucaoEntreUf) {
		this.cdCfopdevolucaoEntreUf = cdCfopdevolucaoEntreUf;
	}

	public Character getStAtivoCompra() {
		return this.stAtivoCompra;
	}

	public void setStAtivoCompra(Character stAtivoCompra) {
		this.stAtivoCompra = stAtivoCompra;
	}

	public Character getStControlaSelo() {
		return this.stControlaSelo;
	}

	public void setStControlaSelo(Character stControlaSelo) {
		this.stControlaSelo = stControlaSelo;
	}

	public Double getFtConversaoClasseEnquadramento() {
		return this.ftConversaoClasseEnquadramento;
	}

	public void setFtConversaoClasseEnquadramento(Double ftConversaoClasseEnquadramento) {
		this.ftConversaoClasseEnquadramento = ftConversaoClasseEnquadramento;
	}

	public String getCdClassificacaoDipi() {
		return this.cdClassificacaoDipi;
	}

	public void setCdClassificacaoDipi(String cdClassificacaoDipi) {
		this.cdClassificacaoDipi = cdClassificacaoDipi;
	}

	public Character getStSujeitoRegimeSubstTribut() {
		return this.stSujeitoRegimeSubstTribut;
	}

	public void setStSujeitoRegimeSubstTribut(Character stSujeitoRegimeSubstTribut) {
		this.stSujeitoRegimeSubstTribut = stSujeitoRegimeSubstTribut;
	}

	public Character getStCompletarEmbalagem() {
		return this.stCompletarEmbalagem;
	}

	public void setStCompletarEmbalagem(Character stCompletarEmbalagem) {
		this.stCompletarEmbalagem = stCompletarEmbalagem;
	}

	public Double getVlLargura() {
		return this.vlLargura;
	}

	public void setVlLargura(Double vlLargura) {
		this.vlLargura = vlLargura;
	}

	public Double getVlRendimento() {
		return this.vlRendimento;
	}

	public void setVlRendimento(Double vlRendimento) {
		this.vlRendimento = vlRendimento;
	}

	public Character getStRestricaoComplQuantIg() {
		return this.stRestricaoComplQuantIg;
	}

	public void setStRestricaoComplQuantIg(Character stRestricaoComplQuantIg) {
		this.stRestricaoComplQuantIg = stRestricaoComplQuantIg;
	}

	public String getCdProdepDipi() {
		return this.cdProdepDipi;
	}

	public void setCdProdepDipi(String cdProdepDipi) {
		this.cdProdepDipi = cdProdepDipi;
	}

	public String getCdSeloControleIpi() {
		return this.cdSeloControleIpi;
	}

	public void setCdSeloControleIpi(String cdSeloControleIpi) {
		this.cdSeloControleIpi = cdSeloControleIpi;
	}

	public String getIdClasseEnquadramento() {
		return this.idClasseEnquadramento;
	}

	public void setIdClasseEnquadramento(String idClasseEnquadramento) {
		this.idClasseEnquadramento = idClasseEnquadramento;
	}

	public String getCdExTipi() {
		return this.cdExTipi;
	}

	public void setCdExTipi(String cdExTipi) {
		this.cdExTipi = cdExTipi;
	}

	public Double getQtUnidadePorSelo() {
		return this.qtUnidadePorSelo;
	}

	public void setQtUnidadePorSelo(Double qtUnidadePorSelo) {
		this.qtUnidadePorSelo = qtUnidadePorSelo;
	}

	public String getIdGeneroProduto() {
		return this.idGeneroProduto;
	}

	public void setIdGeneroProduto(String idGeneroProduto) {
		this.idGeneroProduto = idGeneroProduto;
	}

	public Double getAlCofins() {
		return this.alCofins;
	}

	public void setAlCofins(Double alCofins) {
		this.alCofins = alCofins;
	}

	public Double getAlPis() {
		return this.alPis;
	}

	public void setAlPis(Double alPis) {
		this.alPis = alPis;
	}

	public Character getStAlCofinsporUnidade() {
		return this.stAlCofinsporUnidade;
	}

	public void setStAlCofinsporUnidade(Character stAlCofinsporUnidade) {
		this.stAlCofinsporUnidade = stAlCofinsporUnidade;
	}

	public Character getStAlPisporUnidade() {
		return this.stAlPisporUnidade;
	}

	public void setStAlPisporUnidade(Character stAlPisporUnidade) {
		this.stAlPisporUnidade = stAlPisporUnidade;
	}

	public Character getTpProdutoComplementar() {
		return this.tpProdutoComplementar;
	}

	public void setTpProdutoComplementar(Character tpProdutoComplementar) {
		this.tpProdutoComplementar = tpProdutoComplementar;
	}

	public Character getTpModalidadeBaseSt() {
		return this.tpModalidadeBaseSt;
	}

	public void setTpModalidadeBaseSt(Character tpModalidadeBaseSt) {
		this.tpModalidadeBaseSt = tpModalidadeBaseSt;
	}

	public String getDsPrecoMaximoConsumidor() {
		return this.dsPrecoMaximoConsumidor;
	}

	public void setDsPrecoMaximoConsumidor(String dsPrecoMaximoConsumidor) {
		this.dsPrecoMaximoConsumidor = dsPrecoMaximoConsumidor;
	}

	public Double getVlPrecoMaximoConsumidor() {
		return this.vlPrecoMaximoConsumidor;
	}

	public void setVlPrecoMaximoConsumidor(Double vlPrecoMaximoConsumidor) {
		this.vlPrecoMaximoConsumidor = vlPrecoMaximoConsumidor;
	}

	public Character getStEmiteEtiqueta() {
		return this.stEmiteEtiqueta;
	}

	public void setStEmiteEtiqueta(Character stEmiteEtiqueta) {
		this.stEmiteEtiqueta = stEmiteEtiqueta;
	}

	public Integer getNrDiasValidade() {
		return this.nrDiasValidade;
	}

	public void setNrDiasValidade(Integer nrDiasValidade) {
		this.nrDiasValidade = nrDiasValidade;
	}

	public String getCdListaServico() {
		return this.cdListaServico;
	}

	public void setCdListaServico(String cdListaServico) {
		this.cdListaServico = cdListaServico;
	}

	public byte[] getVersaoRegistro() {
		return this.versaoRegistro;
	}

	public void setVersaoRegistro(byte[] versaoRegistro) {
		this.versaoRegistro = versaoRegistro;
	}

	public String getIdUnidadeComparacao() {
		return this.idUnidadeComparacao;
	}

	public void setIdUnidadeComparacao(String idUnidadeComparacao) {
		this.idUnidadeComparacao = idUnidadeComparacao;
	}

	public Double getFtConversaoComparacao() {
		return this.ftConversaoComparacao;
	}

	public void setFtConversaoComparacao(Double ftConversaoComparacao) {
		this.ftConversaoComparacao = ftConversaoComparacao;
	}

	public Integer getNrTempoExecucaoServico() {
		return this.nrTempoExecucaoServico;
	}

	public void setNrTempoExecucaoServico(Integer nrTempoExecucaoServico) {
		this.nrTempoExecucaoServico = nrTempoExecucaoServico;
	}

	public String getIdServicoSped() {
		return this.idServicoSped;
	}

	public void setIdServicoSped(String idServicoSped) {
		this.idServicoSped = idServicoSped;
	}

	public Double getAlMargemLucro() {
		return this.alMargemLucro;
	}

	public void setAlMargemLucro(Double alMargemLucro) {
		this.alMargemLucro = alMargemLucro;
	}

	public String getCdSituacaoTributariaPis() {
		return this.cdSituacaoTributariaPis;
	}

	public void setCdSituacaoTributariaPis(String cdSituacaoTributariaPis) {
		this.cdSituacaoTributariaPis = cdSituacaoTributariaPis;
	}

	public String getCdSituacaoTributariaCofins() {
		return this.cdSituacaoTributariaCofins;
	}

	public void setCdSituacaoTributariaCofins(String cdSituacaoTributariaCofins) {
		this.cdSituacaoTributariaCofins = cdSituacaoTributariaCofins;
	}

	public Character getStTributacaoEspecifica() {
		return this.stTributacaoEspecifica;
	}

	public void setStTributacaoEspecifica(Character stTributacaoEspecifica) {
		this.stTributacaoEspecifica = stTributacaoEspecifica;
	}

	public String getCdSitTributPissaida() {
		return this.cdSitTributPissaida;
	}

	public void setCdSitTributPissaida(String cdSitTributPissaida) {
		this.cdSitTributPissaida = cdSitTributPissaida;
	}

	public String getCdSitTributCofinssaida() {
		return this.cdSitTributCofinssaida;
	}

	public void setCdSitTributCofinssaida(String cdSitTributCofinssaida) {
		this.cdSitTributCofinssaida = cdSitTributCofinssaida;
	}

	public String getCdSitTributPisentrada() {
		return this.cdSitTributPisentrada;
	}

	public void setCdSitTributPisentrada(String cdSitTributPisentrada) {
		this.cdSitTributPisentrada = cdSitTributPisentrada;
	}

	public String getCdSitTributCofinsentrada() {
		return this.cdSitTributCofinsentrada;
	}

	public void setCdSitTributCofinsentrada(String cdSitTributCofinsentrada) {
		this.cdSitTributCofinsentrada = cdSitTributCofinsentrada;
	}

	public String getNmCurto() {
		return this.nmCurto;
	}

	public void setNmCurto(String nmCurto) {
		this.nmCurto = nmCurto;
	}

	public BigDecimal getFtAcrescimoValorVenda() {
		return this.ftAcrescimoValorVenda;
	}

	public void setFtAcrescimoValorVenda(BigDecimal ftAcrescimoValorVenda) {
		this.ftAcrescimoValorVenda = ftAcrescimoValorVenda;
	}

	public Character getStProdutoIsstributadoIcms() {
		return this.stProdutoIsstributadoIcms;
	}

	public void setStProdutoIsstributadoIcms(Character stProdutoIsstributadoIcms) {
		this.stProdutoIsstributadoIcms = stProdutoIsstributadoIcms;
	}

	public Integer getIdCest() {
		return this.idCest;
	}

	public void setIdCest(Integer idCest) {
		this.idCest = idCest;
	}

	public Double getVlAliquotaPis() {
		return this.vlAliquotaPis;
	}

	public void setVlAliquotaPis(Double vlAliquotaPis) {
		this.vlAliquotaPis = vlAliquotaPis;
	}

	public Double getVlAliquotaCofins() {
		return this.vlAliquotaCofins;
	}

	public void setVlAliquotaCofins(Double vlAliquotaCofins) {
		this.vlAliquotaCofins = vlAliquotaCofins;
	}

	public Character getTpEmbalagem() {
		return this.tpEmbalagem;
	}

	public void setTpEmbalagem(Character tpEmbalagem) {
		this.tpEmbalagem = tpEmbalagem;
	}

	public Double getVlAltura() {
		return this.vlAltura;
	}

	public void setVlAltura(Double vlAltura) {
		this.vlAltura = vlAltura;
	}

	public Double getVlProfundidade() {
		return this.vlProfundidade;
	}

	public void setVlProfundidade(Double vlProfundidade) {
		this.vlProfundidade = vlProfundidade;
	}

	public Double getVlDiametro() {
		return this.vlDiametro;
	}

	public void setVlDiametro(Double vlDiametro) {
		this.vlDiametro = vlDiametro;
	}

	public boolean isStVendaPorTamanho() {
		return this.stVendaPorTamanho;
	}

	public void setStVendaPorTamanho(boolean stVendaPorTamanho) {
		this.stVendaPorTamanho = stVendaPorTamanho;
	}

	public boolean isStSujeitoRegularizacaoSanitaria() {
		return this.stSujeitoRegularizacaoSanitaria;
	}

	public void setStSujeitoRegularizacaoSanitaria(boolean stSujeitoRegularizacaoSanitaria) {
		this.stSujeitoRegularizacaoSanitaria = stSujeitoRegularizacaoSanitaria;
	}

	public String getCdAnvisa() {
		return this.cdAnvisa;
	}

	public void setCdAnvisa(String cdAnvisa) {
		this.cdAnvisa = cdAnvisa;
	}

	public char getTpCalculoQuantidadeEmbalagem() {
		return this.tpCalculoQuantidadeEmbalagem;
	}

	public void setTpCalculoQuantidadeEmbalagem(char tpCalculoQuantidadeEmbalagem) {
		this.tpCalculoQuantidadeEmbalagem = tpCalculoQuantidadeEmbalagem;
	}

	public Date getDtAlteracao() {
		return this.dtAlteracao;
	}

	public void setDtAlteracao(Date dtAlteracao) {
		this.dtAlteracao = dtAlteracao;
	}

	public Integer getIdClassificacaoTelecomunicacao() {
		return this.idClassificacaoTelecomunicacao;
	}

	public void setIdClassificacaoTelecomunicacao(Integer idClassificacaoTelecomunicacao) {
		this.idClassificacaoTelecomunicacao = idClassificacaoTelecomunicacao;
	}

	public boolean isStBloqueiaCriacaoAtendimento() {
		return this.stBloqueiaCriacaoAtendimento;
	}

	public void setStBloqueiaCriacaoAtendimento(boolean stBloqueiaCriacaoAtendimento) {
		this.stBloqueiaCriacaoAtendimento = stBloqueiaCriacaoAtendimento;
	}

	public String getCdBeneficioFiscal() {
		return this.cdBeneficioFiscal;
	}

	public void setCdBeneficioFiscal(String cdBeneficioFiscal) {
		this.cdBeneficioFiscal = cdBeneficioFiscal;
	}

	public String getDsMotivoIsencaoAnvisa() {
		return this.dsMotivoIsencaoAnvisa;
	}

	public void setDsMotivoIsencaoAnvisa(String dsMotivoIsencaoAnvisa) {
		this.dsMotivoIsencaoAnvisa = dsMotivoIsencaoAnvisa;
	}

	public String getIdProdutoOrigemMovimento() {
		return this.idProdutoOrigemMovimento;
	}

	public void setIdProdutoOrigemMovimento(String idProdutoOrigemMovimento) {
		this.idProdutoOrigemMovimento = idProdutoOrigemMovimento;
	}

	public Double getFtConversaoUnidadeMovimento() {
		return this.ftConversaoUnidadeMovimento;
	}

	public void setFtConversaoUnidadeMovimento(Double ftConversaoUnidadeMovimento) {
		this.ftConversaoUnidadeMovimento = ftConversaoUnidadeMovimento;
	}

	public ProdutoPcp getPcp() {
		return pcp;
	}

	public void setPcp(ProdutoPcp pcp) {
		this.pcp = pcp;
	}
	
	public String getCodigo() {
		return this.codigos.stream().findFirst().get().getCdChamada();
	}

	@Override
	public String toString() {
		return "Produto [idProduto=" + idProduto + ", codigos=" + codigos + ", nmProduto=" + nmProduto + ", stAtivo="
				+ stAtivo + "]";
	}
	
	

}
