package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoLoteEmpresaId generated by hbm2java
 */
public class ProdutoLoteEmpresaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idProdutoLote;
	private String idProduto;
	private int cdEmpresa;

	public ProdutoLoteEmpresaId() {
	}

	public ProdutoLoteEmpresaId(String idProdutoLote, String idProduto, int cdEmpresa) {
		this.idProdutoLote = idProdutoLote;
		this.idProduto = idProduto;
		this.cdEmpresa = cdEmpresa;
	}

	public String getIdProdutoLote() {
		return this.idProdutoLote;
	}

	public void setIdProdutoLote(String idProdutoLote) {
		this.idProdutoLote = idProdutoLote;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public int getCdEmpresa() {
		return this.cdEmpresa;
	}

	public void setCdEmpresa(int cdEmpresa) {
		this.cdEmpresa = cdEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoLoteEmpresaId))
			return false;
		ProdutoLoteEmpresaId castOther = (ProdutoLoteEmpresaId) other;

		return ((this.getIdProdutoLote() == castOther.getIdProdutoLote())
				|| (this.getIdProdutoLote() != null && castOther.getIdProdutoLote() != null
						&& this.getIdProdutoLote().equals(castOther.getIdProdutoLote())))
				&& ((this.getIdProduto() == castOther.getIdProduto()) || (this.getIdProduto() != null
						&& castOther.getIdProduto() != null && this.getIdProduto().equals(castOther.getIdProduto())))
				&& (this.getCdEmpresa() == castOther.getCdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProdutoLote() == null ? 0 : this.getIdProdutoLote().hashCode());
		result = 37 * result + (getIdProduto() == null ? 0 : this.getIdProduto().hashCode());
		result = 37 * result + this.getCdEmpresa();
		return result;
	}

}
