package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoLoteSetorId generated by hbm2java
 */
public class ProdutoLoteSetorId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idProdutoLote;
	private String idProduto;
	private String idSetor;

	public ProdutoLoteSetorId() {
	}

	public ProdutoLoteSetorId(String idProdutoLote, String idProduto, String idSetor) {
		this.idProdutoLote = idProdutoLote;
		this.idProduto = idProduto;
		this.idSetor = idSetor;
	}

	public String getIdProdutoLote() {
		return this.idProdutoLote;
	}

	public void setIdProdutoLote(String idProdutoLote) {
		this.idProdutoLote = idProdutoLote;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public String getIdSetor() {
		return this.idSetor;
	}

	public void setIdSetor(String idSetor) {
		this.idSetor = idSetor;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoLoteSetorId))
			return false;
		ProdutoLoteSetorId castOther = (ProdutoLoteSetorId) other;

		return ((this.getIdProdutoLote() == castOther.getIdProdutoLote())
				|| (this.getIdProdutoLote() != null && castOther.getIdProdutoLote() != null
						&& this.getIdProdutoLote().equals(castOther.getIdProdutoLote())))
				&& ((this.getIdProduto() == castOther.getIdProduto()) || (this.getIdProduto() != null
						&& castOther.getIdProduto() != null && this.getIdProduto().equals(castOther.getIdProduto())))
				&& ((this.getIdSetor() == castOther.getIdSetor()) || (this.getIdSetor() != null
						&& castOther.getIdSetor() != null && this.getIdSetor().equals(castOther.getIdSetor())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProdutoLote() == null ? 0 : this.getIdProdutoLote().hashCode());
		result = 37 * result + (getIdProduto() == null ? 0 : this.getIdProduto().hashCode());
		result = 37 * result + (getIdSetor() == null ? 0 : this.getIdSetor().hashCode());
		return result;
	}

}
