package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoPcpEmpresa generated by hbm2java
 */
public class ProdutoPcpEmpresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProdutoPcpEmpresaId id;

	public ProdutoPcpEmpresa() {
	}

	public ProdutoPcpEmpresa(ProdutoPcpEmpresaId id) {
		this.id = id;
	}

	public ProdutoPcpEmpresaId getId() {
		return this.id;
	}

	public void setId(ProdutoPcpEmpresaId id) {
		this.id = id;
	}

}
