package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoPcpCliente generated by hbm2java
 */
public class ProdutoPcpCliente implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProdutoPcpClienteId id;
	private String codFornecedor;
	private String codProdutoCliente;

	public ProdutoPcpCliente() {
	}

	public ProdutoPcpCliente(ProdutoPcpClienteId id) {
		this.id = id;
	}

	public ProdutoPcpCliente(ProdutoPcpClienteId id, String codFornecedor, String codProdutoCliente) {
		this.id = id;
		this.codFornecedor = codFornecedor;
		this.codProdutoCliente = codProdutoCliente;
	}

	public ProdutoPcpClienteId getId() {
		return this.id;
	}

	public void setId(ProdutoPcpClienteId id) {
		this.id = id;
	}

	public String getCodFornecedor() {
		return this.codFornecedor;
	}

	public void setCodFornecedor(String codFornecedor) {
		this.codFornecedor = codFornecedor;
	}

	public String getCodProdutoCliente() {
		return this.codProdutoCliente;
	}

	public void setCodProdutoCliente(String codProdutoCliente) {
		this.codProdutoCliente = codProdutoCliente;
	}

}
