package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoLoteSetor generated by hbm2java
 */
public class ProdutoLoteSetor implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProdutoLoteSetorId id;
	private Double qtPedidoVenda;
	private Double qtProcessamento;
	private Double qtRequisitada;

	public ProdutoLoteSetor() {
	}

	public ProdutoLoteSetor(ProdutoLoteSetorId id) {
		this.id = id;
	}

	public ProdutoLoteSetor(ProdutoLoteSetorId id, Double qtPedidoVenda, Double qtProcessamento, Double qtRequisitada) {
		this.id = id;
		this.qtPedidoVenda = qtPedidoVenda;
		this.qtProcessamento = qtProcessamento;
		this.qtRequisitada = qtRequisitada;
	}

	public ProdutoLoteSetorId getId() {
		return this.id;
	}

	public void setId(ProdutoLoteSetorId id) {
		this.id = id;
	}

	public Double getQtPedidoVenda() {
		return this.qtPedidoVenda;
	}

	public void setQtPedidoVenda(Double qtPedidoVenda) {
		this.qtPedidoVenda = qtPedidoVenda;
	}

	public Double getQtProcessamento() {
		return this.qtProcessamento;
	}

	public void setQtProcessamento(Double qtProcessamento) {
		this.qtProcessamento = qtProcessamento;
	}

	public Double getQtRequisitada() {
		return this.qtRequisitada;
	}

	public void setQtRequisitada(Double qtRequisitada) {
		this.qtRequisitada = qtRequisitada;
	}

}
