package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoLoteEmpresa generated by hbm2java
 */
public class ProdutoLoteEmpresa implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private ProdutoLoteEmpresaId id;
	private Double qtPedidoVenda;
	private Double qtProcessamento;

	public ProdutoLoteEmpresa() {
	}

	public ProdutoLoteEmpresa(ProdutoLoteEmpresaId id) {
		this.id = id;
	}

	public ProdutoLoteEmpresa(ProdutoLoteEmpresaId id, Double qtPedidoVenda, Double qtProcessamento) {
		this.id = id;
		this.qtPedidoVenda = qtPedidoVenda;
		this.qtProcessamento = qtProcessamento;
	}

	public ProdutoLoteEmpresaId getId() {
		return this.id;
	}

	public void setId(ProdutoLoteEmpresaId id) {
		this.id = id;
	}

	public Double getQtPedidoVenda() {
		return this.qtPedidoVenda;
	}

	public void setQtPedidoVenda(Double qtPedidoVenda) {
		this.qtPedidoVenda = qtPedidoVenda;
	}

	public Double getQtProcessamento() {
		return this.qtProcessamento;
	}

	public void setQtProcessamento(Double qtProcessamento) {
		this.qtProcessamento = qtProcessamento;
	}

}
