package br.com.greenwaiver.entities;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoPcp generated by hbm2java
 */
@Entity
@Table(name = "ProdutoPCP", schema = "wpcp")
public class ProdutoPcp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;

	@Id
	private String idProduto;
	private Double vlEspessura;
	private Double vlLargura;
	private Double vlComprimento;
	private String vlConstante;
	private Double vlPeso;
	private Double vlPesoAcrescido;
	private Double vlLado;
	private Double vlArea;
	private Double alPerda;
	private String idTipoFabricacao;
	private Double qtEmbalagemProducao;
	private Double qtEmbalagem;
	private Double qtPeso;
	private String stProducao;
	private String tpProduto;
	private Character stCalcularMetro2;
	private Character stProdutoFantasma;
	private String cor;
	private String diametroT;
	private String diametroE;
	private String diametroI;
	private String diametroH;
	private String diametroB;
	private String diametroHt;
	private String limiteDiametroT;
	private String limiteDiametroE;
	private String limiteDiametroI;
	private String limiteDiametroH;
	private String limiteDiametroB;
	private String limiteDiametroHt;
	private String trefila;
	private String macho;
	private String ponteira;
	private String bucha;
	private String anel;
	private String pino;
	private String cabecote;
	private String entreCentro;
	private String pesoEspecifico;
	private String limitePesoEspecifico;
	private String volumeEspecifico;
	private String limiteVolumeEspec;
	private String qtdEstrutura;
	private String gargalo;
	private String ciclo;
	private String cavidade;
	private String espessura;
	private String limiteEspessura;
	private String diametroH1;
	private String limiteDiametroH1;
	private String molde;
	private Integer setup;
	private Character tpSetup;
	private Character tpCiclo;
	private Double alIneficiencia;

	public ProdutoPcp() {
	}

	public ProdutoPcp(String idProduto) {
		this.idProduto = idProduto;
	}

	public ProdutoPcp(String idProduto, Double vlEspessura, Double vlLargura, Double vlComprimento, String vlConstante,
			Double vlPeso, Double vlPesoAcrescido, Double vlLado, Double vlArea, Double alPerda,
			String idTipoFabricacao, Double qtEmbalagemProducao, Double qtEmbalagem, Double qtPeso, String stProducao,
			String tpProduto, Character stCalcularMetro2, Character stProdutoFantasma, String cor, String diametroT,
			String diametroE, String diametroI, String diametroH, String diametroB, String diametroHt,
			String limiteDiametroT, String limiteDiametroE, String limiteDiametroI, String limiteDiametroH,
			String limiteDiametroB, String limiteDiametroHt, String trefila, String macho, String ponteira,
			String bucha, String anel, String pino, String cabecote, String entreCentro, String pesoEspecifico,
			String limitePesoEspecifico, String volumeEspecifico, String limiteVolumeEspec, String qtdEstrutura,
			String gargalo, String ciclo, String cavidade, String espessura, String limiteEspessura, String diametroH1,
			String limiteDiametroH1, String molde, Integer setup, Character tpSetup, Character tpCiclo,
			Double alIneficiencia) {
		this.idProduto = idProduto;
		this.vlEspessura = vlEspessura;
		this.vlLargura = vlLargura;
		this.vlComprimento = vlComprimento;
		this.vlConstante = vlConstante;
		this.vlPeso = vlPeso;
		this.vlPesoAcrescido = vlPesoAcrescido;
		this.vlLado = vlLado;
		this.vlArea = vlArea;
		this.alPerda = alPerda;
		this.idTipoFabricacao = idTipoFabricacao;
		this.qtEmbalagemProducao = qtEmbalagemProducao;
		this.qtEmbalagem = qtEmbalagem;
		this.qtPeso = qtPeso;
		this.stProducao = stProducao;
		this.tpProduto = tpProduto;
		this.stCalcularMetro2 = stCalcularMetro2;
		this.stProdutoFantasma = stProdutoFantasma;
		this.cor = cor;
		this.diametroT = diametroT;
		this.diametroE = diametroE;
		this.diametroI = diametroI;
		this.diametroH = diametroH;
		this.diametroB = diametroB;
		this.diametroHt = diametroHt;
		this.limiteDiametroT = limiteDiametroT;
		this.limiteDiametroE = limiteDiametroE;
		this.limiteDiametroI = limiteDiametroI;
		this.limiteDiametroH = limiteDiametroH;
		this.limiteDiametroB = limiteDiametroB;
		this.limiteDiametroHt = limiteDiametroHt;
		this.trefila = trefila;
		this.macho = macho;
		this.ponteira = ponteira;
		this.bucha = bucha;
		this.anel = anel;
		this.pino = pino;
		this.cabecote = cabecote;
		this.entreCentro = entreCentro;
		this.pesoEspecifico = pesoEspecifico;
		this.limitePesoEspecifico = limitePesoEspecifico;
		this.volumeEspecifico = volumeEspecifico;
		this.limiteVolumeEspec = limiteVolumeEspec;
		this.qtdEstrutura = qtdEstrutura;
		this.gargalo = gargalo;
		this.ciclo = ciclo;
		this.cavidade = cavidade;
		this.espessura = espessura;
		this.limiteEspessura = limiteEspessura;
		this.diametroH1 = diametroH1;
		this.limiteDiametroH1 = limiteDiametroH1;
		this.molde = molde;
		this.setup = setup;
		this.tpSetup = tpSetup;
		this.tpCiclo = tpCiclo;
		this.alIneficiencia = alIneficiencia;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public Double getVlEspessura() {
		return this.vlEspessura;
	}

	public void setVlEspessura(Double vlEspessura) {
		this.vlEspessura = vlEspessura;
	}

	public Double getVlLargura() {
		return this.vlLargura;
	}

	public void setVlLargura(Double vlLargura) {
		this.vlLargura = vlLargura;
	}

	public Double getVlComprimento() {
		return this.vlComprimento;
	}

	public void setVlComprimento(Double vlComprimento) {
		this.vlComprimento = vlComprimento;
	}

	public String getVlConstante() {
		return this.vlConstante;
	}

	public void setVlConstante(String vlConstante) {
		this.vlConstante = vlConstante;
	}

	public Double getVlPeso() {
		return this.vlPeso;
	}

	public void setVlPeso(Double vlPeso) {
		this.vlPeso = vlPeso;
	}

	public Double getVlPesoAcrescido() {
		return this.vlPesoAcrescido;
	}

	public void setVlPesoAcrescido(Double vlPesoAcrescido) {
		this.vlPesoAcrescido = vlPesoAcrescido;
	}

	public Double getVlLado() {
		return this.vlLado;
	}

	public void setVlLado(Double vlLado) {
		this.vlLado = vlLado;
	}

	public Double getVlArea() {
		return this.vlArea;
	}

	public void setVlArea(Double vlArea) {
		this.vlArea = vlArea;
	}

	public Double getAlPerda() {
		return this.alPerda;
	}

	public void setAlPerda(Double alPerda) {
		this.alPerda = alPerda;
	}

	public String getIdTipoFabricacao() {
		return this.idTipoFabricacao;
	}

	public void setIdTipoFabricacao(String idTipoFabricacao) {
		this.idTipoFabricacao = idTipoFabricacao;
	}

	public Double getQtEmbalagemProducao() {
		return this.qtEmbalagemProducao;
	}

	public void setQtEmbalagemProducao(Double qtEmbalagemProducao) {
		this.qtEmbalagemProducao = qtEmbalagemProducao;
	}

	public Double getQtEmbalagem() {
		return this.qtEmbalagem;
	}

	public void setQtEmbalagem(Double qtEmbalagem) {
		this.qtEmbalagem = qtEmbalagem;
	}

	public Double getQtPeso() {
		return this.qtPeso;
	}

	public void setQtPeso(Double qtPeso) {
		this.qtPeso = qtPeso;
	}

	public String getStProducao() {
		return this.stProducao;
	}

	public void setStProducao(String stProducao) {
		this.stProducao = stProducao;
	}

	public String getTpProduto() {
		return this.tpProduto;
	}

	public void setTpProduto(String tpProduto) {
		this.tpProduto = tpProduto;
	}

	public Character getStCalcularMetro2() {
		return this.stCalcularMetro2;
	}

	public void setStCalcularMetro2(Character stCalcularMetro2) {
		this.stCalcularMetro2 = stCalcularMetro2;
	}

	public Character getStProdutoFantasma() {
		return this.stProdutoFantasma;
	}

	public void setStProdutoFantasma(Character stProdutoFantasma) {
		this.stProdutoFantasma = stProdutoFantasma;
	}

	public String getCor() {
		return this.cor;
	}

	public void setCor(String cor) {
		this.cor = cor;
	}

	public String getDiametroT() {
		return this.diametroT;
	}

	public void setDiametroT(String diametroT) {
		this.diametroT = diametroT;
	}

	public String getDiametroE() {
		return this.diametroE;
	}

	public void setDiametroE(String diametroE) {
		this.diametroE = diametroE;
	}

	public String getDiametroI() {
		return this.diametroI;
	}

	public void setDiametroI(String diametroI) {
		this.diametroI = diametroI;
	}

	public String getDiametroH() {
		return this.diametroH;
	}

	public void setDiametroH(String diametroH) {
		this.diametroH = diametroH;
	}

	public String getDiametroB() {
		return this.diametroB;
	}

	public void setDiametroB(String diametroB) {
		this.diametroB = diametroB;
	}

	public String getDiametroHt() {
		return this.diametroHt;
	}

	public void setDiametroHt(String diametroHt) {
		this.diametroHt = diametroHt;
	}

	public String getLimiteDiametroT() {
		return this.limiteDiametroT;
	}

	public void setLimiteDiametroT(String limiteDiametroT) {
		this.limiteDiametroT = limiteDiametroT;
	}

	public String getLimiteDiametroE() {
		return this.limiteDiametroE;
	}

	public void setLimiteDiametroE(String limiteDiametroE) {
		this.limiteDiametroE = limiteDiametroE;
	}

	public String getLimiteDiametroI() {
		return this.limiteDiametroI;
	}

	public void setLimiteDiametroI(String limiteDiametroI) {
		this.limiteDiametroI = limiteDiametroI;
	}

	public String getLimiteDiametroH() {
		return this.limiteDiametroH;
	}

	public void setLimiteDiametroH(String limiteDiametroH) {
		this.limiteDiametroH = limiteDiametroH;
	}

	public String getLimiteDiametroB() {
		return this.limiteDiametroB;
	}

	public void setLimiteDiametroB(String limiteDiametroB) {
		this.limiteDiametroB = limiteDiametroB;
	}

	public String getLimiteDiametroHt() {
		return this.limiteDiametroHt;
	}

	public void setLimiteDiametroHt(String limiteDiametroHt) {
		this.limiteDiametroHt = limiteDiametroHt;
	}

	public String getTrefila() {
		return this.trefila;
	}

	public void setTrefila(String trefila) {
		this.trefila = trefila;
	}

	public String getMacho() {
		return this.macho;
	}

	public void setMacho(String macho) {
		this.macho = macho;
	}

	public String getPonteira() {
		return this.ponteira;
	}

	public void setPonteira(String ponteira) {
		this.ponteira = ponteira;
	}

	public String getBucha() {
		return this.bucha;
	}

	public void setBucha(String bucha) {
		this.bucha = bucha;
	}

	public String getAnel() {
		return this.anel;
	}

	public void setAnel(String anel) {
		this.anel = anel;
	}

	public String getPino() {
		return this.pino;
	}

	public void setPino(String pino) {
		this.pino = pino;
	}

	public String getCabecote() {
		return this.cabecote;
	}

	public void setCabecote(String cabecote) {
		this.cabecote = cabecote;
	}

	public String getEntreCentro() {
		return this.entreCentro;
	}

	public void setEntreCentro(String entreCentro) {
		this.entreCentro = entreCentro;
	}

	public String getPesoEspecifico() {
		return this.pesoEspecifico;
	}

	public void setPesoEspecifico(String pesoEspecifico) {
		this.pesoEspecifico = pesoEspecifico;
	}

	public String getLimitePesoEspecifico() {
		return this.limitePesoEspecifico;
	}

	public void setLimitePesoEspecifico(String limitePesoEspecifico) {
		this.limitePesoEspecifico = limitePesoEspecifico;
	}

	public String getVolumeEspecifico() {
		return this.volumeEspecifico;
	}

	public void setVolumeEspecifico(String volumeEspecifico) {
		this.volumeEspecifico = volumeEspecifico;
	}

	public String getLimiteVolumeEspec() {
		return this.limiteVolumeEspec;
	}

	public void setLimiteVolumeEspec(String limiteVolumeEspec) {
		this.limiteVolumeEspec = limiteVolumeEspec;
	}

	public String getQtdEstrutura() {
		return this.qtdEstrutura;
	}

	public void setQtdEstrutura(String qtdEstrutura) {
		this.qtdEstrutura = qtdEstrutura;
	}

	public String getGargalo() {
		return this.gargalo;
	}

	public void setGargalo(String gargalo) {
		this.gargalo = gargalo;
	}

	public String getCiclo() {
		return this.ciclo;
	}

	public void setCiclo(String ciclo) {
		this.ciclo = ciclo;
	}

	public String getCavidade() {
		return this.cavidade;
	}

	public void setCavidade(String cavidade) {
		this.cavidade = cavidade;
	}

	public String getEspessura() {
		return this.espessura;
	}

	public void setEspessura(String espessura) {
		this.espessura = espessura;
	}

	public String getLimiteEspessura() {
		return this.limiteEspessura;
	}

	public void setLimiteEspessura(String limiteEspessura) {
		this.limiteEspessura = limiteEspessura;
	}

	public String getDiametroH1() {
		return this.diametroH1;
	}

	public void setDiametroH1(String diametroH1) {
		this.diametroH1 = diametroH1;
	}

	public String getLimiteDiametroH1() {
		return this.limiteDiametroH1;
	}

	public void setLimiteDiametroH1(String limiteDiametroH1) {
		this.limiteDiametroH1 = limiteDiametroH1;
	}

	public String getMolde() {
		return this.molde;
	}

	public void setMolde(String molde) {
		this.molde = molde;
	}

	public Integer getSetup() {
		return this.setup;
	}

	public void setSetup(Integer setup) {
		this.setup = setup;
	}

	public Character getTpSetup() {
		return this.tpSetup;
	}

	public void setTpSetup(Character tpSetup) {
		this.tpSetup = tpSetup;
	}

	public Character getTpCiclo() {
		return this.tpCiclo;
	}

	public void setTpCiclo(Character tpCiclo) {
		this.tpCiclo = tpCiclo;
	}

	public Double getAlIneficiencia() {
		return this.alIneficiencia;
	}

	public void setAlIneficiencia(Double alIneficiencia) {
		this.alIneficiencia = alIneficiencia;
	}

}
