package br.com.greenwaiver.entities;
// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoLoteItem generated by hbm2java
 */
public class ProdutoLoteItem implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idProdutoLoteItem;
	private String idProdutoLote;
	private String idTipoProdutoLoteItem;
	private String nrTipoProdutoLoteItem;

	public ProdutoLoteItem() {
	}

	public ProdutoLoteItem(String idProdutoLoteItem) {
		this.idProdutoLoteItem = idProdutoLoteItem;
	}

	public ProdutoLoteItem(String idProdutoLoteItem, String idProdutoLote, String idTipoProdutoLoteItem,
			String nrTipoProdutoLoteItem) {
		this.idProdutoLoteItem = idProdutoLoteItem;
		this.idProdutoLote = idProdutoLote;
		this.idTipoProdutoLoteItem = idTipoProdutoLoteItem;
		this.nrTipoProdutoLoteItem = nrTipoProdutoLoteItem;
	}

	public String getIdProdutoLoteItem() {
		return this.idProdutoLoteItem;
	}

	public void setIdProdutoLoteItem(String idProdutoLoteItem) {
		this.idProdutoLoteItem = idProdutoLoteItem;
	}

	public String getIdProdutoLote() {
		return this.idProdutoLote;
	}

	public void setIdProdutoLote(String idProdutoLote) {
		this.idProdutoLote = idProdutoLote;
	}

	public String getIdTipoProdutoLoteItem() {
		return this.idTipoProdutoLoteItem;
	}

	public void setIdTipoProdutoLoteItem(String idTipoProdutoLoteItem) {
		this.idTipoProdutoLoteItem = idTipoProdutoLoteItem;
	}

	public String getNrTipoProdutoLoteItem() {
		return this.nrTipoProdutoLoteItem;
	}

	public void setNrTipoProdutoLoteItem(String nrTipoProdutoLoteItem) {
		this.nrTipoProdutoLoteItem = nrTipoProdutoLoteItem;
	}

}
