package br.com.greenwaiver.entities;

import javax.persistence.Embeddable;

// Generated 18 de jun. de 2023 18:46:59 by Hibernate Tools 5.6.14.Final

/**
 * ProdutoEmpresaId generated by hbm2java
 */
@Embeddable
public class ProdutoEmpresaId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idProduto;
	private int cdEmpresa;

	public ProdutoEmpresaId() {
	}

	public ProdutoEmpresaId(String idProduto, int cdEmpresa) {
		this.idProduto = idProduto;
		this.cdEmpresa = cdEmpresa;
	}

	public String getIdProduto() {
		return this.idProduto;
	}

	public void setIdProduto(String idProduto) {
		this.idProduto = idProduto;
	}

	public int getCdEmpresa() {
		return this.cdEmpresa;
	}

	public void setCdEmpresa(int cdEmpresa) {
		this.cdEmpresa = cdEmpresa;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ProdutoEmpresaId))
			return false;
		ProdutoEmpresaId castOther = (ProdutoEmpresaId) other;

		return ((this.getIdProduto() == castOther.getIdProduto()) || (this.getIdProduto() != null
				&& castOther.getIdProduto() != null && this.getIdProduto().equals(castOther.getIdProduto())))
				&& (this.getCdEmpresa() == castOther.getCdEmpresa());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdProduto() == null ? 0 : this.getIdProduto().hashCode());
		result = 37 * result + this.getCdEmpresa();
		return result;
	}

}
